### ISSUE TITLE
Having trouble passing sources

### ISSUE THREAD

**Issue by kgibcc** [DNXLabs/terraform-aws-eks-external-dns#2]
I'd like to deploy with `istio-gateway`, and `istio-virtualservice` added to `sources` as described here

https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/istio.md#configuring-externaldns-to-use-the-istio-gateway-andor-istio-virtual-service-source

However, I'm not able to figure out appropriate code syntax to pass aforementioned values to `external-dns` helm chart.

For example, this
```
  settings = {
    "policy" = "sync" # Modify how DNS records are sychronized between sources and providers.
    "sources" = "[istio-gateway]"
  }
}
```
results in 
```
Error: template: external-dns/templates/deployment.yaml:122:29: executing "external-dns/templates/deployment.yaml" at <.Values.sources>: range can't iterate over [istio-gateway]

  on .terraform/modules/external_dns/helm.tf line 1, in resource "helm_release" "external_dns":
   1: resource "helm_release" "external_dns" {
```

and 
```
  settings = {
    "policy" = "sync" # Modify how DNS records are sychronized between sources and providers.
    "sources" = "service","ingress"
  }
}
```
results in 
```
Error: failed parsing key "sources" with value service, ingress, istio-gateway, istio-virtualservice, key " ingress" has no value (cannot end with ,)

  on .terraform/modules/external_dns/helm.tf line 1, in resource "helm_release" "external_dns":
```

Can you please advise how to set sources?

**Comment by arthurbdiniz** [comment]
Hi @kgibcc,

According to the helm chart documentation this field it's an array. 
https://artifacthub.io/packages/helm/bitnami/external-dns#parameters

The default value for this param is `[service, ingress]`

If you want to add a new param you should specify like this:
```
settings = {
    "policy" = "sync" # Modify how DNS records are sychronized between sources and providers.
    "sources" = [service, ingress, istio-gateway]
}
```

**Comment by kgibcc** [comment]
I believe I tried nearly every combo I could think of there and couldn't get it right.

> Hi @kgibcc,
> 
> According to the helm chart documentation this field it's an array.
> https://artifacthub.io/packages/helm/bitnami/external-dns#parameters
> 
> The default value for this param is `[service, ingress]`
> 
> If you want to add a new param you should specify like this:
> 
> ```
> settings = {
>     "policy" = "sync" # Modify how DNS records are sychronized between sources and providers.
>     "sources" = [service, ingress, istio-gateway]
> }
> ```

returns
```Error: Invalid reference

  on main.tf line 351, in module "external_dns":
 351:     "sources" = [service, ingress, istio-gateway]

A reference to a resource type must be followed by at least one attribute
access, specifying the resource name.


Error: Invalid reference

  on main.tf line 351, in module "external_dns":
 351:     "sources" = [service, ingress, istio-gateway]

A reference to a resource type must be followed by at least one attribute
access, specifying the resource name.
```

**Comment by mosampaio** [comment]
hi @kgibcc , what version are you using?

**Comment by mosampaio** [comment]
Anyway, I believe if you use the latest version (ATTOW, `0.1.4`), and pass an array of strings, it should work. Example:
```
  settings = {
    "policy" = "sync" # Modify how DNS records are sychronized between sources and providers.
    "sources" = ["service", "ingress", "istio-gateway"]
  }
```

**Comment by kgibcc** [comment]
ahh yes, the versions!  that was it, thanks.
