### ISSUE TITLE
AWS 4.x compability

### ISSUE THREAD

**Issue by Lillecarl** [DNXLabs/terraform-aws-eks-external-dns#6]
### Contact Details (optional)

dnxlabs@lillecarl.com

### Description. What happened?

Unable to use AWS 4.x provider.

Is there anything that prevents usage of 4.x? Looking over the resources suggests there shouldn't be issues going 4.x, I assume the constraint was put there before 4.x stabilised, can this be revisited? 😄 

### Steps to reproduce

1. Read version constraints

### Expected behavior

Allowing usage of 4.x

### Actual behavior

Not allowing usage of 4.x

### Occurrence

Frequently

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brunodasilvalenga** [comment]
Related and fix on: https://github.com/DNXLabs/terraform-aws-eks-external-dns/pull/8
